server:
  port: 10010
spring:
  application:
    name: wyzg-api-gateway
  jackson:
    default-property-inclusion:  non_null # 配置json处理时忽略空值
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    user-service: /user/**
    upload-service: /upload/**
    resource-service: /resource/**

  #Zuul中提供了一个ignored-patterns属性，用来忽略不希望路由的URL路径，
  ignored-patterns: /upload/**
  #Zuul还提供了`ignored-services`属性，进行服务过滤
  ignored-services: upload-service


ribbon:
  ConnectTimeout:  250 # 250 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长：10000ms