server:
  port: 8096
spring:
  application:
    name: resource-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wyzg
    username: root
    password: ROOT
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
mybatis:
  configuration:
    map-underscore-to-camel-case: true